name: sql-data-warehouse

services:
  postgres:
    image: postgres:18.1-alpine
    container_name: sql-data-warehouse-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
      - ${HOST_PROJECT_PATH}:/data

  python_dev:
      build:
        # Wskazujemy folder, w którym leżą Dockerfile i requirements.txt
        context: ./docker/python
        dockerfile: dockerfile
      container_name: sql-data-warehouse-python
      depends_on:
        - postgres
      environment:
        # Przekazujemy zmienne dla Pythona
        - DB_HOST=postgres
        - DB_PORT=5432
        - DB_NAME=${POSTGRES_DB}
        - DB_USER=${APP_USER}
        - DB_PASSWORD=${APP_PASSWORD}
      volumes:
        # Montujemy cały Twój folder projektu z kodem Pycharm do /app
        - .:/app
      command: tail -f /dev/null

    # --- NOWY KOMPONENT: AIRFLOW ---
  airflow:
    image: apache/airflow:2.9.1
    container_name: sql-data-warehouse-airflow
    depends_on:
      - postgres
    ports:
      - "8080:8080" # Port dla interfejsu graficznego
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False # Wyłączamy domyślne, śmieciowe DAG-i od Airflow
      # Automatyczna instalacja pakietów przy starcie kontenera do projektów szkoleniowych
      # [!] wydłuża start kontenera i zależy od dostępności zewnętrznych repozytoriów PyPI
      # Zamiast tego buduje się własny obraz (Custom Image) oparty na bazowym obrazie Airflow przy użyciu dedykowanego pliku Dockerfile.
      - _PIP_ADDITIONAL_REQUIREMENTS=great_expectations python-dotenv psycopg2-binary SQLAlchemy pandas dbt-postgres
      # ... inne zmienne konfiguracyjne Airflow ...
      - APP_USER=${APP_USER}
      - APP_PASSWORD=${APP_PASSWORD}
    volumes:
      - ./dags:/opt/airflow/dags  # Montujemy folder z naszymi DAG-ami
      - ./tests:/opt/airflow/tests
      - ./.env:/opt/airflow/.env
      - ./docs:/opt/airflow/docs
      - ./dbt_project:/opt/airflow/dbt_project  #dbt
    command: standalone
volumes:
  postgres_data: