# dbt_project/dbt_project.yml
name: 'data_warehouse'
version: '1.0.0'
config-version: 2
profile: 'dwh_profile'

model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

models:
  data_warehouse:
    silver:
      +materialized: table # DROP TABLE oraz INSERT INTO Domyślnie wszystkie modele stworzą fizyczne tabele (zastępując stare przy każdym uruchomieniu)
      +persist_docs:
        relation: true
        columns: true
    gold:
      +materialized: view
      +schema: gold # Dodany parametr kierujący widoki do schematu gold
      +persist_docs:
        relation: true
        columns: true