version: 2
models:
  - name: crm_cust_info
    config:
      contract:
        enforced: true
    data_tests:
      - min_row:
          arguments:
            min_row_cnt: 1000000
    description: 'Stores customer information'
    columns:
      - name: cst_id
        data_type: integer
        description: 'Unique numerical identifier assigned to each customer'
        data_tests:
          - unique
          - not_null
      - name: cst_key
        data_type: varchar(50)
        description: 'Alphanumeric identifier representing the customer'
        data_tests:
          - relationships:
              arguments:
                to: ref('erp_cust_az12')
                field: cid
              severity: warn
      - name: cst_firstname
        data_type: string
        description: 'The customer''s first name, as recorded in the system'
      - name: cst_lastname
        data_type: string
        description: 'The customer''s last name or family name'
      - name: cst_marital_status
        data_type: string
        description: 'The marital status of the customer'
        data_tests:
          - accepted_values:
              arguments:
                values: ['Singlex','Marriedx']
              severity: error
      - name: cst_gndr
        data_type: string
        description: 'The gender of the customer'
      - name: cst_create_date
        data_type: date
        description: 'The date and time when the customer record was created in the system'
        data_tests:
          - create_cust_date_test